/**
 * Constantes de privilegios (deben coincidir con Privilegio.nombre en backend).
 *
 * Nota: se usan para navegación/guards. La autorización real siempre la decide el backend.
 */
export const OpPrivilegioConstants = {
  // Visualización
  VER_CONTENIDO_PUBLICO: 'VER_CONTENIDO_PUBLICO',
  VER_CONTENIDO_PROPIO: 'VER_CONTENIDO_PROPIO',
  VER_CONTENIDO_RESTRINGIDO: 'VER_CONTENIDO_RESTRINGIDO',
  VER_DASHBOARD: 'VER_DASHBOARD',

  // Entradas
  CREAR_ENTRADAS: 'CREAR_ENTRADAS',
  EDITAR_ENTRADAS_PROPIAS: 'EDITAR_ENTRADAS_PROPIAS',
  EDITAR_ENTRADAS_TODO: 'EDITAR_ENTRADAS_TODO',
  PUBLICAR_ENTRADAS: 'PUBLICAR_ENTRADAS',
  BORRAR_ENTRADAS: 'BORRAR_ENTRADAS',

  // Comentarios
  COMENTAR: 'COMENTAR',
  MODERAR_COMENTARIOS: 'MODERAR_COMENTARIOS',

  // Gestión
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS',
  GESTIONAR_ROLES_USUARIOS: 'GESTIONAR_ROLES_USUARIOS',
  GESTIONAR_PRIVILEGIOS: 'GESTIONAR_PRIVILEGIOS',
  GESTIONAR_PERFIL: 'GESTIONAR_PERFIL',
  GESTIONAR_ARCHIVOS: 'GESTIONAR_ARCHIVOS',
  GESTIONAR_ETIQUETAS: 'GESTIONAR_ETIQUETAS',
  GESTIONAR_CATEGORIAS: 'GESTIONAR_CATEGORIAS',
  GESTIONAR_PAGINAS: 'GESTIONAR_PAGINAS',

  // Config/Mantenimiento
  CONFIGURAR_SISTEMA: 'CONFIGURAR_SISTEMA',
  REALIZAR_MANTENIMIENTO: 'REALIZAR_MANTENIMIENTO',
  DEPURAR_ERRORES: 'DEPURAR_ERRORES',
  GESTIONAR_APIS: 'GESTIONAR_APIS',
} as const;
