import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  SidebarModule,
  NavbarModule,
  NavModule,
  CardModule,
  ButtonModule,
  ListGroupModule,
  FooterModule,
  HeaderModule,
  GridModule,
  BadgeModule,
  DropdownModule,
  AvatarModule,
  FormModule,
  TableModule,
  BreadcrumbModule,
  AlertModule,
  ModalModule,
  SpinnerModule,
  ToastModule,
  UtilitiesModule,
} from '@coreui/angular';

@NgModule({
  imports: [
    CommonModule,
    SidebarModule,
    NavbarModule,
    NavModule,
    CardModule,
    ButtonModule,
    ListGroupModule,
    FooterModule,
    HeaderModule,
    GridModule,
    BadgeModule,
    DropdownModule,
    AvatarModule,
    FormModule,
    TableModule,
    BreadcrumbModule,
    ToastModule,
    ModalModule,
    SpinnerModule,
    UtilitiesModule,
    CardModule,
    GridModule,
    AlertModule,
  ],
  exports: [
    CommonModule,
    SidebarModule,
    NavbarModule,
    NavModule,
    CardModule,
    ButtonModule,
    ListGroupModule,
    FooterModule,
    HeaderModule,
    GridModule,
    BadgeModule,
    DropdownModule,
    AvatarModule,
    FormModule,
    TableModule,
    BreadcrumbModule,
    ToastModule,
    ModalModule,
    SpinnerModule,
    UtilitiesModule,
    CardModule,
    GridModule,
    AlertModule,
  ],
})
export class SharedCoreUiModule {}
